# In-process provider configuration
apiVersion: core.openfeature.dev/v1beta1
kind: InProcessConfiguration
metadata:
  name: in-process-config
spec:
  host: flagd-in-process
---
# Deployment for our application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toggle-shop-deployment
  labels:
    app: toggle-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toggle-shop
  template:
    metadata:
      labels:
        app: toggle-shop
      annotations:
        openfeature.dev/enabled: 'true'
        openfeature.dev/inprocessconfiguration: 'in-process-config'
    spec:
      containers:
        - name: toggle-shop
          image: ghcr.io/open-feature/toggle-shop:v0.3.1 # x-release-please-version
          ports:
            - containerPort: 3000
              name: app-port
          env:
            - name: FLAGD_HOST
              value: flagd-in-process
            - name: OTLP_TRACE_URL
              value: http://toggle-shop-otel-collector.toggle-shop.svc.cluster.local:4317
            - name: OTLP_METRICS_URL
              value: http://toggle-shop-otel-collector.toggle-shop.svc.cluster.local:4317
            - name: OTLP_LOGS_URLs
              value: http://toggle-shop-otel-collector.toggle-shop.svc.cluster.local:4317
---
# Service to expose our application
apiVersion: v1
kind: Service
metadata:
  name: toggle-shop-app-service
  labels:
    app: toggle-shop
spec:
  type: ClusterIP
  selector:
    app: toggle-shop
  ports:
    - port: 3000
      targetPort: app-port
---
# Ingress for our application
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: toggle-shop-ingress
spec:
  parentRefs:
    - name: default-envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - toggle-shop.reining.dev
  rules:
    - backendRefs:
        - kind: Service
          name: toggle-shop-app-service
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - group: ""
          kind: Service
          name: flagd-ui
          namespace: open-feature-toggle-shop
          port: 8016
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /api/ofrep
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /ofrep
    - backendRefs:
        - group: ""
          kind: Service
          name: flagd-ui
          namespace: open-feature-toggle-shop
          port: 8013
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /api/flagd.evaluation.v1.Service
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /flagd.evaluation.v1.Service
