apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfeature-operator
  namespace: argocd
spec:
  destination:
    namespace: open-feature-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: of-operator/deployment
    repoURL: {{GITOPS_REPO}}
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
