apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-feature-demo-otel
  namespace: open-feature-demo
spec:
  image: jaegertracing/jaeger:2.3.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      jaeger_storage_exporter:
        trace_storage: in_memory
    extensions:
      jaeger_query:
        storage:
          traces: in_memory
      jaeger_storage:
        backends:
          in_memory:
            memory:
              max_traces: 100000
      healthcheckv2:
        use_v2: true
        http:
          endpoint: "localhost:13133"
          status:
            enabled: true
            path: "/health/status"
    service:
      extensions: [jaeger_storage, jaeger_query, healthcheckv2]
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ jaeger_storage_exporter ]
        metrics:
          receivers: [ otlp ]
          exporters: [ prometheus ]
  managementState: managed
