apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: open-feature-demo-otel
  namespace: open-feature-demo
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    extensions:
      health_check: {}
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlp:
        endpoint: jaeger-collector.open-feature-demo.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      extensions: [health_check]
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ ]
          exporters: [ otlp ]
        metrics:
          receivers: [ otlp ]
          processors: [ ]
          exporters: [ prometheus ]
