apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipt
  namespace: open-feature-demo
  labels:
    app: flipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipt
  template:
    metadata:
      labels:
        app: flipt
    spec:
      initContainers:
        - name: flipt-init
          image: docker.flipt.io/flipt/flipt:v1.42.1
          command: [ "./flipt", "import", "/var/opt/flipt/flags.yml" ]
          volumeMounts:
            - name: flags
              mountPath: "/var/opt/flipt"
              readOnly: true
            - name: db
              mountPath: "/var/opt/flipt/db"
              readOnly: false
          env:
            - name: FLIPT_LOG_LEVEL
              value: "debug"
            - name: FLIPT_META_TELEMETRY_ENABLED
              value: "false"
            - name: FLIPT_DB_URL
              value: "/var/opt/flipt/db/flipt.db"
      containers:
        - name: flipt
          image: docker.flipt.io/flipt/flipt:v1.42.1
          command: [ "./flipt", "--force-migrate" ]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: db
              mountPath: "/var/opt/flipt/db"
              readOnly: false
          env:
            - name: FLIPT_CORS_ENABLED
              value: "true"
            - name: FLIPT_TRACING_ENABLED
              value: "true"
            - name: FLIPT_TRACING_EXPORTER
              value: "otlp"
            - name: FLIPT_TRACING_OTLP_ENDPOINT
              value: "http://open-feature-demo-otel-collector.open-feature-demo.svc.cluster.local:4317"
            - name: FLIPT_DB_URL
              value: "/var/opt/flipt/db/flipt.db"
      volumes:
        - name: flags
          configMap:
            name: flipt-flags
            items:
              - key: flags.yml
                path: flags.yml
        - name: db
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-flipt-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: flipt
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flipt-flags
  namespace: open-feature-demo
data:
  flags.yml: |
    version: "1.2"
    namespace: default
    flags:
      - key: new-welcome-message
        name: new-welcome-message
        type: BOOLEAN_FLAG_TYPE
        description: Controls the welcome banner message
        enabled: true
        rollouts:
          - threshold:
              percentage: 100
              value: true
      - key: hex-color
        name: hex-color
        type: VARIANT_FLAG_TYPE
        description: Controls the UI color
        enabled: true
        variants:
          - key: c05543
            name: red
          - key: 2f5230
            name: green
          - key: 0d507b
            name: blue
          - key: d4ac0d
            name: yellow
        rules:
          - segment: Signed-In-Users
            distributions:
              - variant: d4ac0d
                rollout: 100
          - segment: All-Users
            distributions:
              - variant: 2f5230
                rollout: 100
      - key: use-remote-fib-service
        name: use-remote-fib-service
        type: BOOLEAN_FLAG_TYPE
        description: Controls whether the remote fib service is used
        enabled: true
        rollouts:
          - segment:
              key: Signed-In-Users
              value: true
          - segment:
              key: All-Users
      - key: fib-algo
        name: fib-algo
        type: VARIANT_FLAG_TYPE
        description: The algorithm to calculate the fibbonaci sequence
        enabled: true
        variants:
          - key: binet
            name: binet
          - key: memo
            name: memo
          - key: loop
            name: loop
          - key: recursive
            name: recursive
        rules:
          - segment: All-Users
            distributions:
              - variant: memo
                rollout: 100
    segments:
      - key: All-Users
        name: All Users
        description: All users are matched
        match_type: ALL_MATCH_TYPE
      - key: Signed-In-Users
        name: Signed In Users
        description: Users that are signed in
        constraints:
          - type: STRING_COMPARISON_TYPE
            property: email
            operator: suffix
            value: '@faas.com'
        match_type: ALL_MATCH_TYPE
