apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-ingress
  namespace: open-feature-demo
  annotations:
    cert-manager.io/cluster-issuer: reining-dev-prod-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://of-cloud-native.reining.dev, https://*.of-cloud-native.reining.dev"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Connect-Protocol-Version"
spec:
  ingressClassName: nginx
  rules:
    - host: of-cloud-native.reining.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-feature-demo-service
                port:
                  number: 80
  tls:
    - hosts:
        - of-cloud-native.reining.dev
      secretName: of-demo-server-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-flagd-ingress
  namespace: open-feature-demo
  annotations:
    cert-manager.io/cluster-issuer: reining-dev-prod-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://of-cloud-native.reining.dev, https://*.of-cloud-native.reining.dev"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Connect-Protocol-Version"
spec:
  ingressClassName: nginx
  rules:
    - host: flagd.of-cloud-native.reining.dev
      http:
        paths:
          - path: /ofrep
            pathType: Prefix
            backend:
              service:
                name: flagd-ofrep-service
                port:
                  number: 80
  tls:
    - hosts:
        - flagd.of-cloud-native.reining.dev
      secretName: of-demo-server-flagd-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-flagd-grpc-ingress
  namespace: open-feature-demo
  annotations:
    cert-manager.io/cluster-issuer: reining-dev-prod-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://of-cloud-native.reining.dev, https://*.of-cloud-native.reining.dev"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Connect-Protocol-Version"
spec:
  ingressClassName: nginx
  rules:
    - host: flagd.of-cloud-native.reining.dev
      http:
        paths:
          - path: /flagd.evaluation.v1.Service
            pathType: Prefix
            backend:
              service:
                name: flagd-grpc-service
                port:
                  number: 80
  tls:
    - hosts:
        - flagd.of-cloud-native.reining.dev
      secretName: of-demo-server-flagd-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-goff-ingress
  namespace: open-feature-demo
  annotations:
    cert-manager.io/cluster-issuer: reining-dev-prod-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://of-cloud-native.reining.dev, https://*.of-cloud-native.reining.dev"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Connect-Protocol-Version"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: goff.of-cloud-native.reining.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-feature-demo-goff-service
                port:
                  number: 1031
  tls:
    - hosts:
        - goff.of-cloud-native.reining.dev
      secretName: of-demo-server-goff-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-flipt-ingress
  namespace: open-feature-demo
  annotations:
    cert-manager.io/cluster-issuer: reining-dev-prod-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://of-cloud-native.reining.dev, https://*.of-cloud-native.reining.dev"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Connect-Protocol-Version"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: flipt.of-cloud-native.reining.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-feature-demo-flipt-service
                port:
                  number: 8080
  tls:
    - hosts:
        - flipt.of-cloud-native.reining.dev
      secretName: of-demo-server-flipt-tls
---
