apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-playground-app
  namespace: open-feature-demo
  labels:
    app: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo
  template:
    metadata:
      labels:
        app: open-feature-demo
      annotations:
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: "end-to-end"
    spec:
      containers:
        - name: open-feature-demo
          image: ghcr.io/open-feature/playground-app:v0.15.2
          args:
            - flagd
          ports:
            - containerPort: 30000
          envFrom:
            - configMapRef:
                name: open-feature-demo-config
            - configMapRef:
                name: open-feature-demo-env-flag-config
          env:
            - name: HARNESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: harness-key
                  optional: true
            - name: HARNESS_KEY_WEB
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: harness-key-web
                  optional: true
            - name: LD_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: ld-key
                  optional: true
            - name: LD_KEY_WEB
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: ld-key-web
                  optional: true
            - name: SPLIT_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: split-key
                  optional: true
            - name: SPLIT_KEY_WEB
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: split-key-web
                  optional: true
            - name: CLOUDBEES_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: cloudbees-key
                  optional: true
            - name: CLOUDBEES_APP_KEY_WEB
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: cloudbees-key-web
                  optional: true
            - name: FLAGSMITH_ENV_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: flagsmith-key
                  optional: true
            - name: FLAGSMITH_ENV_KEY_WEB
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: flagsmith-key-web
                  optional: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open-feature-demo-config
  namespace: open-feature-demo
data:
  OTEL_COLLECTOR_URL: "http://open-feature-demo-otel-collector.open-feature-demo.svc.cluster.local:4317"
  FIB_SERVICE_URL: "http://open-feature-fibonacci-service.open-feature-demo.svc.cluster.local:30000"
  FLAGD_HOST: "localhost"
  FLAGD_PORT: "8013"
  FLAGD_TLS: "false"
  FLAGD_HOST_WEB: "flagd.of-cloud-native.reining.dev"
  FLAGD_TLS_WEB: "true"
  FLAGD_PORT_WEB: "443"
  FLAGD_OFREP_TLS_WEB: "true"
  FLAGD_OFREP_PORT_WEB: "443"
  GO_FEATURE_FLAG_URL: "http://open-feature-demo-goff-service.open-feature-demo.svc.cluster.local:1031"
  GO_FEATURE_FLAG_WEB_URL: "https://goff.of-cloud-native.reining.dev"
  NODE_ENV: "production"
  # OTEL_LOG_LEVEL: "DEBUG"
---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-ofrep-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8016
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-grpc-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8013
