apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-feature-demo
  namespace: argocd
spec:
  destination:
    namespace: open-feature-demo
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://helm.flipt.io
      chart: flipt
      targetRevision: 0.72.1
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          persistence:
            enabled: true
          flipt:
            extraEnvVars:
              - name: FLIPT_CORS_ENABLED
                value: "true"
              - name: FLIPT_TRACING_ENABLED
                value: "true"
              - name: FLIPT_TRACING_EXPORTER
                value: "otlp"
              - name: FLIPT_TRACING_OTLP_ENDPOINT
                value: "http://open-feature-demo-otel-collector.open-feature-demo.svc.cluster.local:4317"
            config:
              cors:
                enabled: true
    - path: cloud-native-demo/deployment
      repoURL: {{GITOPS_REPO}}
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
