apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfeature-demo
  namespace: argocd
spec:
  destination:
    namespace: open-feature-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cloud-native-demo/deployment
    repoURL: {{GITOPS_REPO}}
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
